CROP_MAP = {
    'arecanut': 'coconut',
    'arhar/tur': 'pigeonpeas',
    'castor seed': 'sesamum',
    'cotton(lint)': 'cotton',
    'dry chillies': 'chili',
    'gram': 'chickpea',
    'linseed': 'mustard',
    'mesta': 'jute',
    'niger seed': 'sesamum',
    'onion': 'onion',
    'other  rabi pulses': 'lentil',
    'rapeseed &mustard': 'mustard',
    'sesamum': 'sesamum',
    'small millets': 'mothbeans',
    'sweet potato': 'potato',
    'tapioca': 'cassava',
    'tobacco': 'tobacco',
    'turmeric': 'turmeric',
    'wheat': 'wheat',
    'bajra': 'pearl millet',
    'black pepper': 'pepper',
    'cardamom': 'cardamom',
    'coriander': 'coriander',
    'garlic': 'garlic',
    'ginger': 'ginger',
    'groundnut': 'groundnut',
    'horse-gram': 'horsegram',
    'jowar': 'sorghum',
    'ragi': 'finger millet',
    'cashewnut': 'cashew',
    'soyabean': 'soybean',
    'sugarcane': 'sugarcane',
    'barley': 'barley',
    'khesari': 'lentil',
    'masoor': 'lentil',
    'moong(green gram)': 'mungbean',
    'other kharif pulses': 'blackgram',
    'safflower': 'sunflower',
    'sannhamp': 'sunflower',
    'sunflower': 'sunflower',
    'urad': 'blackgram',
    'peas & beans (pulses)': 'kidneybeans',
    'other oilseeds': 'mustard',
    'other cereals': 'maize',
    'potato': 'potato',
    'cowpea(lobia)': 'cowpea',
    'guar seed': 'cluster beans',
    'oilseeds total': 'mustard',
    'other summer pulses': 'mungbean',
    'moth': 'mothbeans'
}

CROP_SOIL_MAP = {
    'pigeonpeas': 'loamy',
    'sesamum': 'sandy loam',
    'chili': 'sandy loam',
    'mustard': 'loamy',
    'jute': 'alluvial',
    'onion': 'sandy loam',
    'lentil': 'clay loam',
    'mothbeans': 'sandy',
    'cassava': 'laterite',
    'tobacco': 'sandy loam',
    'pearl millet': 'sandy',
    'cardamom': 'forest soil',
    'groundnut': 'sandy loam',
    'horsegram': 'red',
    'sorghum': 'black',
    'blackgram': 'loamy',
    'sunflower': 'loamy',
    'kidneybeans': 'clay loam',
    'cowpea': 'sandy loam',
    'cluster beans': 'sandy',
    'banana': 'loamy'
}
